Repository vuestorefront/magento2, pull requests merged in 2022-07, with the labels that each got.

#1304 fix: product review form offscreen issue
  packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue
Labels: bug

#1305 fix: command correction according to markshust script
  docs/installation-setup/configure-magento.md
Labels: bug, documentation

#1306 test: browsing product load test
  .eslintignore
  packages/load-tests/src/scenarios/browsingProduct.js
  packages/load-tests/src/scenarios/searchProduct.js
  packages/load-tests/src/scenarios/utils/setDefaultCookies.js
Labels: vsf_team
